"""Prepare the archived MAME SVG for the browser without changing any paths."""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET
root_dir = Path(__file__).resolve().parent.parent
ns = '{http://www.w3.org/2000/svg}'
ET.register_namespace('', ns[1:-1])
source = ET.parse(root_dir / 'assets/lcd.svg').getroot()
svg = ET.Element(ns+'svg', {'viewBox': source.attrib['viewBox'], 'preserveAspectRatio': 'none', 'aria-hidden': 'true'})
layer = next(e for e in source if e.get('id') == 'layer1')
svg.append(layer)
count = 0
for element in layer.iter():
    title = element.find(ns+'title')
    if title is not None and re.fullmatch(r'[0-8]\.[0-3]\.[01]', title.text or ''):
        group, bit, common = map(int, title.text.split('.'))
        element.set('data-segment', str(group * 8 + bit * 2 + common))
        element.set('data-pin', title.text)
        element.remove(title)
        count += 1
    for key in list(element.attrib):
        if key.startswith('{'): del element.attrib[key]
assert count == 72, f'Expected 72 LCD segments; found {count}'
markup = ET.tostring(svg, encoding='unicode')
(root_dir/'js/artwork.js').write_text('// Archived MAME LCD paths. Generated by scripts/prepare-artwork.py.\nconst NP_ARTWORK = '+json.dumps(markup, ensure_ascii=False)+';\n')
print(f'Prepared {count} LCD segments')
